org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.210
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=map_show
mod_name=Map Show
mod_license=AGPLv3

mod_version=1.0.1
mod_group_id=org.hismeo.map_show
mod_authors=KalebLangley, Westernat
mod_description=

systemProp.http.proxyHost=localhost
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=7890
